### ISSUE TITLE
DataGenerator class not found

### ISSUE THREAD

**Issue by Vincent9797** [peachman05/action-recognition-tutorial#2]
I am trying to recreate your work. However, I found that the DataGenerator class in data_gen.py is not included in your repo. Could you provide that class in your repo?

**Comment by peachman05** [comment]
Oh sure, I've already added data_gen.py and weight.hdf5. I think It's okay now for running the demo and evaluation

**Comment by Vincent9797** [comment]
Thanks. It works now.
